# =============================================================================
# SENSORS - Music dashboard (media_player.office)
# =============================================================================
# Subscribes to media_player attributes and updates LVGL labels, bar, image,
# and play/pause icon. To use a different entity, override in your main YAML
# with a package override or use a local copy and set entity_id.
# Album art base URL: http://192.168.1.30:8123 (path from HA already includes token).
# =============================================================================

text_sensor:
  - platform: homeassistant
    entity_id: media_player.office
    id: media_title_sensor
    attribute: media_title
    on_value:
      - lvgl.label.update:
          id: media_title_label
          text: !lambda 'return x.empty() ? std::string("—") : x;'

  - platform: homeassistant
    entity_id: media_player.office
    id: media_artist_sensor
    attribute: media_artist
    on_value:
      - lvgl.label.update:
          id: media_artist_label
          text: !lambda 'return x.empty() ? std::string("—") : x;'

  - platform: homeassistant
    entity_id: media_player.office
    id: media_entity_picture_sensor
    attribute: entity_picture
    on_value:
      - if:
          condition:
            lambda: 'return !x.empty();'
          then:
            - online_image.set_url:
                id: album_art_image
                url: !lambda |-
                  std::string path = x;
                  while (!path.empty() && (path.back() == '\n' || path.back() == '\r' || path.back() == ' ')) path.pop_back();
                  return std::string("http://192.168.1.30:8123") + path;

  - platform: homeassistant
    entity_id: media_player.office
    id: media_player_state_sensor
    on_value:
      - lvgl.label.update:
          id: media_play_pause_icon
          text: !lambda |-
            if (x == "playing") return std::string("\xEF\x83\xA4");  // mdi-pause U+F03E4
            return std::string("\xEF\x84\x8D");  // mdi-play U+F040D

sensor:
  - platform: homeassistant
    entity_id: media_player.office
    id: media_duration_sensor
    attribute: media_duration
    on_value:
      - lvgl.label.update:
          id: media_duration_label
          text: !lambda |-
            char buf[12];
            int sec = (int)x;
            if (sec < 0) sec = 0;
            int m = sec / 60;
            int s = sec % 60;
            snprintf(buf, sizeof(buf), "%02d:%02d", m, s);
            return std::string(buf);

  - platform: homeassistant
    entity_id: media_player.office
    id: media_position_sensor
    attribute: media_position
    on_value:
      - lvgl.label.update:
          id: media_elapsed_label
          text: !lambda |-
            char buf[12];
            int sec = (int)x;
            if (sec < 0) sec = 0;
            int m = sec / 60;
            int s = sec % 60;
            snprintf(buf, sizeof(buf), "%02d:%02d", m, s);
            return std::string(buf);
      - lvgl.bar.update:
          id: media_progress_bar
          value: !lambda |-
            float pos = x;
            float dur = id(media_duration_sensor).state;
            if (dur > 0) {
              return (int)((pos / dur) * 100.0f);
            }
            return 0;
